// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schiavello.Data;

namespace Schiavello.Migrations
{
    [DbContext(typeof(ListDbContext))]
    [Migration("20220513092301_Initial Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Schiavello.Data.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("List");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Name = "Test",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "test2",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "test3",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "test4",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
